"""Core API for safecmd"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core.ipynb.

# %% auto 0
__all__ = ['cmd_groups', 'ok_cmds', 'find_spec', 'ok_ops', 'run', 'CmdSpec', 'add_cmds', 'validate_cmd', 'DisallowedOps',
           'DisallowedCmd', 'safe_run']

# %% ../nbs/01_core.ipynb 1
import subprocess,json,shutil
from .bashxtract import *
from fastcore.utils import *

# %% ../nbs/01_core.ipynb 10
def run(cmd, ignore_ex=False):
    "Run `cmd` in shell; return stdout (+ stderr if any); raise IOError on failure"
    res = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    out = res.stdout.strip()
    if res.stderr: out += ('\n' if out else '') + res.stderr.strip()
    if ignore_ex: return (res.returncode, out)
    if res.returncode: raise IOError(out)
    return out

# %% ../nbs/01_core.ipynb 15
class CmdSpec(BasicRepr):
    def __init__(self,
        name,  # the command (str, will be split into tuple)
        denied=None):  # if set, these flags blocked
        self.name = tuple(name.split())
        self.denied = set(denied or [])

    def __hash__(self): return hash(self.name)
    def __eq__(self, b): return self.name==b.name
    
    def __repr__(self):
        s = ' '.join(self.name)
        if self.denied: s += f' !{self.denied}'
        return s
    
    def __call__(self, toks):
        "Returns True if allowed, False if no match or denied flag found"
        if tuple(toks[:len(self.name)]) != self.name: return False
        return not (self.denied and self.denied & set(toks))

# %% ../nbs/01_core.ipynb 19
def add_cmds(*cmds):
    ok_cmds.update(c if isinstance(c, CmdSpec) else CmdSpec(c) for c in cmds)

# %% ../nbs/01_core.ipynb 22
cmd_groups = {
    'File viewing': ['cat', 'head', 'tail', 'less', 'more', 'bat'],
    'Directory listing': ['ls', 'tree', 'locate'],
    'Search': ['grep', 'rg', 'ag', 'ack', 'fgrep', 'egrep'],
    'Text processing': ['cut', 'sort', 'uniq', 'wc', 'tr', 'column'],
    'File info': ['file', 'stat', 'du', 'df', 'which', 'whereis', 'type'],
    'Comparison': ['diff', 'cmp', 'comm'],
    'Archives': ['tar', 'unzip', 'gunzip', 'bunzip2', 'unrar'],
    'Network': ['curl', 'wget', 'ping', 'dig', 'nslookup', 'host'],
    'System info': ['date', 'cal', 'uptime', 'whoami', 'hostname', 'uname', 'env', 'printenv'],
    'Utilities': ['echo', 'printf', 'yes', 'seq', 'basename', 'dirname', 'realpath'],
    'Git (read-only)': ['git log', 'git show', 'git diff', 'git status', 'git branch', 'git tag', 'git remote', 'git stash list', 'git blame', 'git shortlog', 'git describe', 'git rev-parse', 'git ls-files', 'git ls-tree', 'git cat-file', 'git config --get', 'git config --list'],
    'Git (workspace)': ['git fetch', 'git add', 'git commit', 'git switch', 'git checkout'],
}

ok_cmds = set()

for v in cmd_groups.values(): add_cmds(*v)
find_spec = CmdSpec('find', denied=['-exec', '-execdir', '-delete', '-ok', '-okdir'])
add_cmds(find_spec)

# %% ../nbs/01_core.ipynb 27
ok_ops = {'|', '<', '&&', '||', ';'}

# %% ../nbs/01_core.ipynb 31
def validate_cmd(toks, cmds=None):
    "Check if toks matches an allowed command; returns False if denied flags present"
    if cmds is None: cmds = ok_cmds
    return any(spec(toks) for spec in cmds)

# %% ../nbs/01_core.ipynb 34
class DisallowedOps(PermissionError):
    def __init__(self, ops): super().__init__(f"Disallowed operators: {ops}")

class DisallowedCmd(PermissionError):
    def __init__(self, cmd): super().__init__(f"Disallowed command: {' '.join(cmd)}")

def safe_run(cmd, cmds=None, ops=None):
    "Run `cmd` in shell if all commands and operators are in allowlists, else raise"
    if ops is None: ops = ok_ops
    commands, used_ops = extract_commands(cmd)
    if bad_ops := used_ops - ops: raise DisallowedOps(bad_ops)
    for c in commands:
        if not validate_cmd(c, cmds): raise DisallowedCmd(c)
    return run(cmd)
